Add Spring Security with LDAP and JWT authentication
Comcast/dawg pull request #23
Opened 2017-01-03 23:07 UTC by kpears201

2017-01-03 23:34 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/AuthServerConfig.java
> +	private String ldapDomain = "dc=dawg,dc=comcast,dc=com";
comcast specific... might want to move it out to a config file

2017-01-04 00:00 UTC, kpears201 commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/AuthServerConfig.java
> +	private String ldapDomain = "dc=dawg,dc=comcast,dc=com";
It does come from a config file, this is the default. Guess I could remove the default.

2017-01-04 06:06 UTC, dimaj requested changes
Could you also add some javadocs, please?

2017-01-04 06:06 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/AuthServerConfig.java
> +	private String ldapDomain = "dc=dawg,dc=comcast,dc=com";
I think that since this is an external copy, there should be as little reference to Comcast as possible

2017-01-04 06:06 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/service/LdapUserService.java
> +			connection = new LdapNetworkConnection( config.getLdapHost(), 389 );
ldap could be listening on another port (especially if ldap is NATed or if it's ldaps). port should also come from config. Config could assume `389` as default if port is not specified

2017-01-04 06:06 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/service/LdapUserService.java
> +			this.connection.bind("cn=" + config.getLdapBindCn() + "," + config.getLdapDomain(), config.getLdapBindPassword());
instead of doing this, why not ask user to provide `bind username` and `password`.

2017-01-04 06:06 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/service/LdapUserService.java
> +
did you mean to assign config to `this.config`?

2017-01-04 06:06 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/service/LdapUserService.java
> +			String userdn = "uid=" + user.getUid() + ",ou=people," + config.getLdapDomain();
please, don't assume that all users are under `ou=people`.

2017-01-04 06:06 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/service/LdapUserService.java
> +				String dn = "cn=" + role + ",ou=group," + config.getLdapDomain();
same as above, let these locations be specified by user in the config.

2017-01-04 06:06 UTC, dimaj commented on libraries/dawg-house/src/main/java/com/comcast/video/dawg/controller/house/WebSecurityConfig.java
> +            .contextSource().url("ldap://" + authCfg.getLdapHost() + ":" + authCfg.getLdapPort())
why are you locking users into `ldap://`? I would suggest that users specify ldap url (e.g. `ldaps://localhost:12348`, `ldap://localhost:389`, etc)
User should also specify in the config:
* base DN for searching (e.g. `ou=People,dc=domain,dc=com`)
* search base
* filter (if any)
Here's a sample config file for LDAP configuration (https://github.com/gitlabhq/gitlabhq/blob/master/config/gitlab.yml.example#L235)

2017-01-04 06:06 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/service/LdapUserService.java
> +        putIfNotNull(person, "userPassword", sha(user.getPassword()));
why are you locking people into using `sha`

2017-01-04 17:24 UTC, kpears201 commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/service/LdapUserService.java
> +        putIfNotNull(person, "userPassword", sha(user.getPassword()));
Actually, I guess the LDAP server can just do the hashing, people can configure their ldap server to whatever algorithm they want then. Our app shouldn't need to handle this. I will change it so it gets sent to the LDAP server non-hashed.

2017-01-04 17:24 UTC, kpears201 commented on libraries/dawg-house/src/main/java/com/comcast/video/dawg/controller/house/WebSecurityConfig.java
> +            .contextSource().url("ldap://" + authCfg.getLdapHost() + ":" + authCfg.getLdapPort())
k I will make all these configurable.

2017-01-05 01:37 UTC, kpears201 reviewed
I've made the requested changes.
However, after reading more about password encoding: Spring is urging to use BCrypt as password encoding and have deprecated support for the other digest encodings, so that is what I have gone with.
If people have existing LDAP systems that use other password encodings (eg. SHA, SSHA, MD5) then they should add a feature to support those. Due to the small chance others are going to be using dawg and with existing LDAPs, lets just do what works for us and have others complete the features if necessary.

2017-01-06 23:07 UTC, merged