Adding default rackProxyUrl and rackProxyEnabled to dawg.ini for dawg…
Comcast/dawg pull request #26
Opened 2017-01-23 23:32 UTC by kpears201

…-show

2017-01-23 23:54 UTC, dimaj requested changes
Build is failing

2017-01-23 23:54 UTC, dimaj commented on libraries/dawg-common/src/main/java/com/comcast/video/dawg/common/MetaStb.java
> +        Object rpe = data.get(MetaStb.RACK_PROXY_ENABLED);
why is `toString` important here?

2017-01-23 23:54 UTC, dimaj commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/jwt/JwtDevicePopulator.java
> +import java.util.Timer;
is this needed here?

2017-01-23 23:54 UTC, dimaj commented on libraries/dawg-show/src/main/java/com/comcast/video/dawg/show/PowerController.java
> +        MetaStb meta = new MetaStb(new HashMap<String, Object>(stb.getData())); // make a copy so we can set some defaults
it seems like this block is repeated 3 times... do you think it would be a good idea to factor it out? Maybe have a new class `DefaultMetaStb`?

2017-01-24 03:14 UTC, kpears201 commented on libraries/dawg-server-common/src/main/java/com/comcast/video/dawg/common/security/jwt/JwtDevicePopulator.java
> +import java.util.Timer;
oops, no

2017-01-24 03:15 UTC, kpears201 commented on libraries/dawg-common/src/main/java/com/comcast/video/dawg/common/MetaStb.java
> +        Object rpe = data.get(MetaStb.RACK_PROXY_ENABLED);
setRackProxyEnabled stores the field as a boolean. So if you do a get after a set you will get a class cast exception.

2017-01-24 03:19 UTC, kpears201 commented on libraries/dawg-show/src/main/java/com/comcast/video/dawg/show/PowerController.java
> +        MetaStb meta = new MetaStb(new HashMap<String, Object>(stb.getData())); // make a copy so we can set some defaults
considered it, pretty low amount of repeated code. But maybe it makes enough sense.

2017-01-24 03:58 UTC, kpears201 commented on libraries/dawg-show/src/main/java/com/comcast/video/dawg/show/PowerController.java
> +        MetaStb meta = new MetaStb(new HashMap<String, Object>(stb.getData())); // make a copy so we can set some defaults
made the change

2017-01-24 04:01 UTC, merged